package com.danchen.biblio.hibernate.bean;

// Generated Nov 22, 2013 6:45:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Article generated by hbm2java
 */
public class Article implements java.io.Serializable {

	private Integer id;
	private Article article;
	private User user;
	private Date time;
	private Integer parent;
	private Integer state;
	private String content;
	private String title;
	private Set<Tag> tags = new HashSet(0);
	private Set<Article> children = new HashSet(0);

	public Article() {
	}

	public Article(User user, Date time, int state) {
		this.user = user;
		this.time = time;
		this.state = state;
	}

	public Article(Article article,Integer parent, User user, Date time, int state,
			String content, String title, Set tags, Set articles) {
		this.article = article;
		this.parent = parent;
		this.user = user;
		this.time = time;
		this.state = state;
		this.content = content;
		this.title = title;
		this.tags = tags;
		this.children = articles;
	}

	public Integer getParent() {
		return parent;
	}

	public void setParent(Integer parent) {
		this.parent = parent;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Set getTags() {
		return this.tags;
	}

	public void setTags(Set tags) {
		this.tags = tags;
	}

	public Set getChildren() {
		return this.children;
	}

	public void setChildren(Set articles) {
		this.children = articles;
	}

}
