package com.danchen.biblio.hibernate.bean;

// Generated Nov 22, 2013 6:45:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

import org.hibernate.annotations.OrderBy;

/**
 * Article generated by hbm2java
 */
public class Article implements java.io.Serializable {

	private Integer id;
	private User user;
	private Date time;
	private Integer parent;
	private Integer topic;
	private Integer state;
	private String content;
	private String title;
	private Set<Tag> tags = new HashSet(0);
	private Set<Article> children = new TreeSet();
	private Set<Article> posts = new TreeSet();

	public Article() {
	}

	public Article(Integer id) {
		this.id = id;
	}
	
	public Article(User user, Date time, Integer parent, Integer topic, int state,
			String content, String title, Set<Tag> tags) {
		this.user = user;
		this.time = time;
		this.parent = parent;
		this.topic = topic;
		this.state = state;
		this.content = content;
		this.title = title;
		this.tags = tags;
	}

	public Integer getParent() {
		return parent;
	}

	public void setParent(Integer parent) {
		this.parent = parent;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Set getTags() {
		return this.tags;
	}

	public void setTags(Set tags) {
		this.tags = tags;
	}

	public Set getChildren() {
		return this.children;
	}

	public void setChildren(Set articles) {
		this.children = articles;
	}

	public Integer getTopic() {
		return topic;
	}
	public void setTopic(Integer topic) {
		this.topic = topic;
	}

	public Set<Article> getPosts() {
		return posts;
	}
	public void setPosts(Set<Article> posts) {
		this.posts = posts;
	}
	
	public Date getPostTime(){
		if(getPosts().size() > 0)
			return getPosts().iterator().next().getTime();
		else
			return time;
	}

}
