package com.danchen.biblio.hibernate.bean;

// Generated Nov 22, 2013 6:45:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Set;
import java.util.TreeSet;

/**
 * Tag generated by hbm2java
 */
public class Tag implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set articles = new TreeSet();

	public Tag() {
	}

	public Tag(String name) {
		this.name = name;
	}

	public Tag(String name, Set articles) {
		this.name = name;
		this.articles = articles;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getArticles() {
		return this.articles;
	}

	public void setArticles(Set articles) {
		this.articles = articles;
	}

}
