package com.danchen.biblio.model;

// Generated Nov 21, 2013 4:45:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tag generated by hbm2java
 */
public class Tag implements java.io.Serializable {

	private Integer id;
	private String name;
	private String chtname;
	private Set articles = new HashSet(0);

	public Tag() {
	}

	public Tag(String name) {
		this.name = name;
	}

	public Tag(String name, String chtname, Set articles) {
		this.name = name;
		this.chtname = chtname;
		this.articles = articles;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getChtname() {
		return this.chtname;
	}

	public void setChtname(String chtname) {
		this.chtname = chtname;
	}

	public Set getArticles() {
		return this.articles;
	}

	public void setArticles(Set articles) {
		this.articles = articles;
	}

}
